CREATE DATABASE krks02_warsztat2
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

CREATE TABLE user_group(
id INT AUTO_INCREMENT,
name VARCHAR(255) UNIQUE,
PRIMARY KEY(id)
);

CREATE TABLE users(
id INT AUTO_INCREMENT,
username VARCHAR(255) UNIQUE,
email VARCHAR(255) UNIQUE,
password VARCHAR(255),
person_group_id INT,
PRIMARY KEY(id),
FOREIGN KEY(person_group_id)
REFERENCES user_group(id)
ON DELETE CASCADE
);